### ISSUE TITLE
[sysops] PRS Fire Wall Script and Guide for Allinia

### ISSUE THREAD

**Issue by kiranh-logicmatter** [logicmatter/FacilityCare#5]
TASKS: All tasks that were done for the sysops work 
- [x] Update Firewall guide below for Firewall testing for Allina
 - [PRS FIlrewall Guide / Doc ](https://docs.google.com/document/d/1EdfOsiZ_sd83nFKQE8VH9uVeCDp6CVga/edit#heading=h.t7ersjsqch1i)
- [ ] Create script and updated the guide below for Firewall testing for Allina
 - [Location of PRS Filrewall Guide and Script ](https://drive.google.com/drive/u/0/search?q=PRS%20v2%20Firewall)

# Prepare and Test
- [ ] After Testing share this information with Kiran to send to Allina

>>>>

----

**Comment by rajeshs-logicmatter** [comment]
Updated the FIrewall guide, please review it.
[](https://docs.google.com/document/d/1EdfOsiZ_sd83nFKQE8VH9uVeCDp6CVga/edit#heading=h.1fob9te)

**Comment by support-logicmatter** [comment]
I reviewed the guide and also edit it before sending the guide to Matt.


Here is the recent guide


*[PRS Firewall Guide 2.0 ](https://docs.google.com/document/d/11iZTyQMp-x8QnBWxJ4t3waTXYRpBplNq5wnEK-c22yg/edit)*
